name: Test commit

on:
  push:
    branches: [ main, rc ]
  pull_request:
    branches: [ main, rc ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Test Build      
        run: |
          ver=$(cat Cargo.toml | grep -m1 version | grep  -Eo '["\047].*["\047]' | tr -d '"')
          echo $ver
          cargo test
